### ISSUE TITLE
Broken nightly

### ISSUE THREAD

**Issue by arielshaqed** [binaris/builder-function#4]
https://ci.binaris.io/blue/organizations/jenkins/nightly/detail/nightly/1321/pipeline

**Comment by arielshaqed** [comment]
No relevant git tags, so cannot tag it.  (Not sure why `nightly` does _not_ try to build the function, then _does_ try to tag it.

**Comment by vogre** [comment]
This is again a mismatch between https://github.com/binaris/precious/blob/master/services.groovy and https://github.com/binaris/precious/blob/master/known_repos

**Comment by vogre** [comment]
Should be fixed by https://github.com/binaris/precious/pull/445.
